### ISSUE TITLE
BOP Prioritization on Miro - Will

### ISSUE THREAD

**Issue by MasSamH** [civictechindex/BOP#126]
### Overview
We need your help with a quick prioritization of features that define usability  (3-5 min)

### Details
We are working on an evaluation of the current BOP's usability and how useable other organizations playbooks are.  In order to complete this analysis we have to establish how we define usability.  We have identified 9 criteria.  Please help us sort them in order of importance.

### Action Items

- [ ]  @willpfeffer Using the instructions in the video below, use Miro to prioritize the cards.

### Resources/Instructions
[Miro Board](https://miro.com/app/board/o9J_kgJShaA=/)
[How to sort the cards for prioritizing the final report video](https://www.awesomescreenshot.com/video/2663274?key=ca3d0687b3fa493528b0104afc7dfe68)

**Comment by MasSamH** [comment]
Slacked Will 02.01.21.

**Comment by Baleja** [comment]
Blockers: Explanation video needed from @Baleja

**Comment by willpfeffer** [comment]
I'm finished with this
